<?php

?>

<h1><?= Yii::t('{module_translation_base}.admin', 'Welcome to {module_title}'); ?></h1>

<p>This page was generated by the Module Editor. Please edit this text manually in the view file.</p>